Rewrite threading client
* REF: Move more brains into Subscriptions to avoid race condition.

* REF: We do not need to lock to send.

* TST: Add an 'ioc_factory' fixture to re-starting an IOC with one test.

* TST: Refactor test_server_crash to use the ioc_factory fixture.

* TMP: Skip the epics-base variant of test_server_crash due to unrelated problem.

* REF: Remove potential for race condition by being more specific about which PVs need circuits.

* TST: Verify the subscriptions are revived after reconnection.

* MNT: remove independent 'connected' state on compat layer

* DOC: Leave note for @tacaswell.

* ENH/FIX/TST: Fix and test unsubscribe; do it automatically when last callback is removed.

* MNT: be a bit more careful about maybe-dead PVs

* STY: Flake8 police / Arrest this man / He talks in maths

* TST: Add a test for multiple PVs with the same name at different priority.

* FIX: Fix mistake, allowing previously committed test to pass.

* TST: Test that nothing bad happens if two IOCs have the same PV.

* TST: more subscriptions testing -- no fixes

* TST: more subscriptions testing

* TST: minor change for clarity

* TST: Test that Subscription objects are reused when identical subscriptions are requested.

* REF: Reuse cached Subscriptions when an identical sub is requested.

* CLN: Remove unused import.

* FIX: Remove subscriptionid from cache on receipt on EventCancelResponse.

* MNT: Fix up repr.

* MNT: Use a lower max datagram size.

On a stock Ubuntu 16.04 VM, a random Virtual circuit disconnect
caused caproto to reissue search requests in bulk for the many PVs
on an area detector. This exposed that our max datagram size is
too high for stock Ubuntu. See error pasted below.

CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "172.17.0.2:34405"
    Source File: ../cac.cpp line 1223
    Current Time: Thu May 03 2018 09:22:09.448894990
..................................................................
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/dallan/miniconda3/envs/dd/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dallan/miniconda3/envs/dd/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dallan/caproto/caproto/threading/client.py", line 531, in _retry_unanswered_searches
    self.send(ca.EPICS_CA1_PORT, ca.VersionRequest(0, 13), *batch)
  File "/home/dallan/caproto/caproto/threading/client.py", line 384, in send
    self.udp_sock.sendto(bytes_to_send, (host, port))
OSError: [Errno 90] Message too long

* FIX: Avoid race condition in pyepics_shim PV init.

The connection callback was being run before the __init__ had a
chance to set self._caproto_pv. There was no way to fix this by
reordering the statements in __init__, but since the callback
itself passes caproto_pv in as an argument, we can just get it
from there rather than relying on access to it in instance state.

* MNT: be more precise with callback locks

* MNT: move udp selector up

* DOC: Document the 7 threads that the client has.

* REF: Give lock a better name.

* FIX: Protect PV.channel and PV.circuit_manager with locks.

* FIX: Wait for the connection callback to set the PV.channel attr.

* WIP: Eh?

* WIP: Meh.

* MNT: more locking

* MNT: yet more locks

* FIX: Lock more narrowly around pvs_needing_circuits.

* FIX: typo

* SUF: shuffling the deckchairs

* FIX: rookie mistake

* MNT: I don't think that works the way you think it works

* HACK: remove __del__ for now

* FIX: we must be getting tired

* FIX: Move the connection check around the actual send.

* ENH: Add unsubscribe_all in case that is useful to cleanup.

* API: Rethink what users are allowed to do with a Subscription.

* all the debugging

* MNT: trigger the re-connect _after_ we kill the socket

* MNT: we have killed the socket, replace it with None

* MNT: lock unsubscribe

* MNT: prune the subscriptions more aggressively

* CI: make logs on travis better

* MNT: remove excessive prints

* REF: Dial back the whimsy but only a little.

* FIX: Simplify and let subscriptionid removal happen on confirmation.

* FIX: Fix up removal of defunct subscriptionids.

* FIX: We need a CONNECTED Channel not just any Channel.

* FIX: not a thing

* TST: Keep a ref to calblack to avoid failure by gc.

* FIX: Track whether circuit has been torn down as separate state.

* MNT: unsubscribe -> clear

* CLN: failure due to flake8

* REF: more events!

* FIX: add use_notify for write

* REF: further tweak use_complete/writenotifyresponse

* MNT: oops, rebase-me

* API: Switch to put completion off by default.

* API/TST: Make use_notify a bit magical but document it well.

* REF: Remove last_reading and last_writing in favor of ioid matching.

* REF: add close event for contexts and broadcaster

* DOC: Update docstrings to suggest ChannelType instead of DBR_* classes.

* CLN: Make read() and write() signatures specific (not args, kwargs).

* MNT: Do not call read/write callbacks if respones arrive after timeout.

* FIX/TST: Test timeout behavior and accept timeout=None.

* FIX: Update caget_many to not use now-removed 'last_reading'.

* STY: freeze this is the style police

* TST: Verify that the context fixture cleans up it threads during teardown.

* FIX: Search-result processing thread never cleaned up.

* ENH: add more locks on pyepics compat layer

* TST: Clean up SharedBroadcaster fixture and check that it kills its threads.

* FIX: Clean up some SharedBroadcaster threads (more left to do).

* TST: Finish verifying that every Context and SharedBroadcaster thread is dead.

* API: Do not auto-kill unused SharedBroadcaster. Make private names consistent.

* DOC: Break down which objects have which threads.

* FIX: apply to-scalar logic earlier

If the value is a length 1 array, store the scalar version in
`_args['value']`.  The original returned value is available in
`_args['raw_value']`

* FIX: spelling

* REF/CLN: Use a ThreadPoolExecutor and remove unused code.

* FIX: lock not needed in __init__

* ENH: threading access rights callbacks

* TST: Make test_timeout more reliable.

* REF: Send _all_ searches from the _retry_unanswered_seraches_thread.

* FIX: The search loop has no chill.

* ENH: warn when getting duplicate search results

* FIX: typo

* WIP: Consolidate code paths and reduce number of locks.

* REF: Drawing inspiration from ThreadPoolExecutor.shutdown(), join threads on clean.

* REF: Send all EventAddRequest through same thread.

* REF: No need for new_command_cond or waiting on VC disconnect.

* TST: add some initial multithreading tests

* TST: Finish test_multithreaded_many_write.

* TST: Space out them writes, cowboy.

* DOC: Change default worker count to 1 and provide warning in comment about increasing it.

* FIX: the activate_subscriptions loop has no chill.

* TST: Poll readiness in test_server.py as well.

* FIX: match pyepics behavior of not auto-monitoring

* BLD: set minimum version of python

* BLD: add classifiers

closes #181

* TST: fix PV Context in access tests

* MNT: match default value of pyepics

* STY: flake8