MNT: Use a lower max datagram size.
On a stock Ubuntu 16.04 VM, a random Virtual circuit disconnect
caused caproto to reissue search requests in bulk for the many PVs
on an area detector. This exposed that our max datagram size is
too high for stock Ubuntu. See error pasted below.

CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "172.17.0.2:34405"
    Source File: ../cac.cpp line 1223
    Current Time: Thu May 03 2018 09:22:09.448894990
..................................................................
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/dallan/miniconda3/envs/dd/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dallan/miniconda3/envs/dd/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dallan/caproto/caproto/threading/client.py", line 531, in _retry_unanswered_searches
    self.send(ca.EPICS_CA1_PORT, ca.VersionRequest(0, 13), *batch)
  File "/home/dallan/caproto/caproto/threading/client.py", line 384, in send
    self.udp_sock.sendto(bytes_to_send, (host, port))
OSError: [Errno 90] Message too long